# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install npm depdencies
    init: |
      npm i -g npm
    command: |
      npm i
      sleep 30
      npm run start:dev
  - name: Docker
    init: |
      docker-compose pull
    command: |
      docker-compose up
      

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true

image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - "asciidoctor.asciidoctor-vscode"
