POST http://localhost:3000/github
token: ASDFASDF
content-type: application/json

{
  "username": "string",
  "bio": "string",
  "avatarUrl": "string",
  "followers": 0,
  "repos": 0,
  "organization": "string",
  "location": "string",
  "blog": "string",
  "event": "workflow_dispatch"
}
