apiVersion: apps/v1
kind: Deployment
metadata:
  name: eddiehub-api-deployment
  labels:
    app: eddiehub-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eddiehub-api
  template:
    metadata:
      labels:
        app: eddiehub-api
    spec:
      volumes:
        - name: mongo-crt
          secret:
            secretName: mongo-crt
      containers:
        - name: api
          image: ghcr.io/eddiehubcommunity/api:latest
          volumeMounts:
            - mountPath: '/etc/mongo/crt'
              name: mongo-crt
              readOnly: true
          ports:
            - containerPort: 3000
          env:
            - name: APPROVED_TOKENS
              valueFrom:
                secretKeyRef:
                  name: approved-tokens
                  key: APPROVED_TOKENS
            - name: API_MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: api-mongo-connection-string
                  key: API_MONGO_CONNECTION_STRING
            - name: API_MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: api-mongo-db-name
                  key: API_MONGO_DB_NAME
            - name: GH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gh-token
                  key: GH_TOKEN
            - name: API_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-webhook-secret
                  key: API_WEBHOOK_SECRET
