== Authentication

There are two authentication-methods within the API. The following chapter shall give an overview on how to create and then use the generated tokens for making requests to the API.

=== Tokens

The API uses two kinds of tokens. +
Please take a look at the Swagger-Documentation of the API to see which tokens needs to be provided for using which endpoint.

* **API-Token:** 
** The API-Token is a static token, which gets set in the environment-variables as `APPROVED_TOKENS`. 
** This token is used to authenticate a 'admin-App' against the API. The API-Token is used to generate **Bearer-Tokens**. 
** When using the API-Token to access an endpoint, it needs to be provided within the `Client-Token`-Header of the Request.
** For generating more than one token they can be passed to the environment-variables as a comma-seperated list.
* **Bearer-Token**
** The Bearer-Token contains the **keyspace**, **Client-ID** and **Scopes**
** Currenty there are two Scopes available `Data.Read` and `Data.Write`
** Client-ID is a unique UUID, which gets generated when generating a new token
** The **Keyspace** is the ServerID of the Discord-Bot which consumes the API
** **!IMPORTANT** currently Datastax Astra isn't able to generate a new Keyspace on the fly. Therefor the keyspace needs to be created manually before being able to use a new one.
** When using a Bearer-Token to access an endpoint, it needs to be provided with the `Authorization`-Header as a `Bearer-Token`
